import Head from "next/head";
import Link from "next/link";
import { FormEvent, useState } from "react";
import Navbar from "../components/navbar";
// import { ProposalList } from "../components/proposalList";
// import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";
import DAOlogo from "../temp_assets/THUBA_logo.png";

// import FileUpload from "../components/fileUpload";

export default function Home() {

    interface DAOBriefInterface {
        logoURL: string;
        name: string;
        introduction: string;
        treasuryAddress: string;
        access: string;
    }

    interface UserInfoInterface {
        userAddress: string;
        profileList: Array<DAOBriefInterface>;
        // subAdminList: Array<DAOBriefInterface>;
        // memberList: Array<DAOBriefInterface>;
    }

    const daoTestData: UserInfoInterface = {
        userAddress: "0x18928391",
        profileList: [
            {
                // logoURL: "htp://.,..,.",
                logoURL: "https://bobbyhadz.com/images/blog/react-display-image-from-url/banner.webp",
                name: "THUBA DAO",
                introduction: "introduction here",
                treasuryAddress: "0xjasiejif",
                access: "admin"
            },
            {
                // logoURL: "htp://.,..,.",
                logoURL: "https://images.unsplash.com/photo-1598124146163-36819847286d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
                name: "BIT DAO",
                introduction: "introduction here",
                treasuryAddress: "0xjasiejif",
                access: "admin"
            },
            {
                logoURL: "https://bobbyhadz.com/images/blog/react-display-image-from-url/banner.webp",
                name: "Something DAO",
                introduction: "introduction here",
                treasuryAddress: "0xjasiejif",
                access: "subadmin"
            },
            {
                logoURL: "https://bobbyhadz.com/images/blog/react-display-image-from-url/banner.webp",
                name: "Brian DAO",
                introduction: "introduction here",
                treasuryAddress: "0xjasiejif",
                access: "member"
            }
        ]
    }
    const handleDAOSubmit = () => {
        console.log(" in handle submit function")
    }

    // const { isMember, isStakeholder, loading } = useData();
    // if (loading) return <div>Loading...</div>;
    return (
        <>
        <div className={styles.container}>
            <Head>
                <title>DAOmocles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar
                isCreate={true}
            />
            <main className="w-full flex flex-col py-4 flex-grow max-w-8xl items-center" style={{ width: "95%" }}>
                <div className={styles.incomingoutgoing} style={{ padding: "50px" }}>

                    <div className={styles.settingsgrid} style={{ gridTemplateColumns: "50% 50%" }}>
                        <div>Upload DAO Logo</div>
                        <div>
                            {/* <FileUpload></FileUpload> */}
                        </div>

                        <div style={{ marginTop: "8px" }}>DAO Name</div>
                        <input type="text" id="small-input" style={{ marginLeft: "3px" }} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500"></input>
                        <div style={{ marginTop: "8px" }}>Introduction</div>
                        <textarea id="message" rows="4" style={{ marginLeft: "3px" }} className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder=""></textarea>
                        <div style={{ marginTop: "8px" }}>Treasury Address</div>
                        <input type="text" id="small-input" style={{ marginLeft: "3px" }} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-gray-500 focus:border-gray-500 block w-full p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-gray-500 dark:focus:border-gray-500"></input>
                    </div>
                    <div>
                        <a href="/daolist">
                            <button
                                className={styles.confirmbutton}
                                onClick={() => {
                                    handleDAOSubmit()
                                    console.log("created")
                                }}
                            >
                                Confirm
                            </button>
                        </a>
                    </div>
                </div>
            </main>

        </div >
        </>
    );
}
