import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";

export default function Home() {


    return (
        <div className={styles.container}>
            <Head>
                <title style={{ fontSize: "5rem" }}>DAOmocles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar
                isCreate={true}
            />
            <div style={{marginBottom:"5rem"}}>
                <div style={{ fontSize: "4rem", textAlign: "center", marginBottom:"1rem" }}>DAOmocles for your treasury management</div>
                <div style={{ fontSize: "1.7rem", textAlign: "center", marginBottom:"8rem", color:"#B98BE8" }}> To request access to DAOmocles, please connect your wallet</div>
                <a href='/daolist' style={{ marginTop:"5rem", marginLeft:"40%", padding:"1rem", paddingLeft:"2rem",paddingRight:"2rem", borderRadius:"15px", backgroundColor:"#B98BE8",fontSize: "2rem", textAlign: "center"}}> Launch App </a>
            </div>
        </div >
    );
}
