import Head from "next/head";
import { FormEvent, useState } from "react";
import Navbar from "../components/navbar";
import SettingNavbar from "../components/settingnavbar";

// import { ProposalList } from "../components/proposalList";
// import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";
import DAOlogo from "../temp_assets/THUBA_logo.png";

export default function Home() {
    const queryParameters = new URLSearchParams(window.location.search)
    const daoname = queryParameters.get("DAO")
    console.log("edit progfiles", daoname)
    return (
        <div className={styles.container}>
            <Head>
                <title>DAOmocles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar
                daoname={daoname}
            />
            <SettingNavbar
                daoname={daoname}
            />
            <div className={styles.settings} style={{ height: "450px", marginBottom: "3rem" }}>
                <div className={styles.settingsgrid}>
                    <div className={styles.one}>
                        <img src={require("../temp_assets/THUBA_logo.png")} alt="" />
                    </div>
                    <div className={styles.two}>
                        Upload Logo Module
                    </div>
                    <div className={styles.three}>DAO Name</div>
                    <input className={styles.four}></input>
                    <div className={styles.five}>Introduction</div>
                    <input className={styles.six}></input>
                </div>
                <div>
                    <button className={styles.confirmbutton}>Confirm</button>
                </div>
            </div>
        </div>
    );
}