import Head from "next/head";
import { FormEvent, useState } from "react";
import Navbar from "../components/navbar";
import SettingNavbar from "../components/settingnavbar";
// import { ProposalList } from "../components/proposalList";
// import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";

export default function Home() {
    const queryParameters = new URLSearchParams(window.location.search)
    const daoname = queryParameters.get("DAO")
    return (
        <div className={styles.container}>
            <Head>
                <title>DAOmocles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar
                daoname={daoname}
            />
            <SettingNavbar
                daoname={daoname}
            />
            <div className={styles.settings} style={{ height: "450px", marginBottom: "3rem" }}>
                <div className={styles.settingsgrid}>

                    <div className={styles.one}>Account Address</div>
                    <input className={styles.two}></input>
                    <div className={styles.three}>Permissions</div>
                    <div className={styles.four}>
                        <select name="Networks" id="networks">
                            <option value="Ethereum">Owner</option>
                            <option value="Polygon">Editor</option>
                            <option value="Mantle">Viewer</option>
                        </select>
                    </div>
                    <div className={styles.seven}>+ Add Another Token</div>
                </div>
                <div>
                    <button className={styles.confirmbutton}>Confirm</button>
                </div>
            </div>
        </div>
    );
}