import Head from "next/head";
import { FormEvent, useState } from "react";
import Navbar from "../components/navbar";
// import { ProposalList } from "../components/proposalList";
// import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [amount, setAmount] = useState("");
  const [isEdit, setIsEdit] = useState(false);
  const [editText, setEditText] = useState("Edit");
  const [recipient, setRecipient] = useState("");
  const [image, setImage] = useState<File | null>();
  // const { createProposal } = useData();

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    var id;
    if (image) {
      let formData = new FormData();
      formData.append("image", image);
      var res = await fetch("/api/upload-image", {
        method: "POST",
        body: formData,
      });
      var data = await res.json();
      id = data.id;
    }
    // await createProposal({
    //   title,
    //   description,
    //   amount,
    //   recipient,
    //   imageId: id ?? "",
    // });
    setTitle("");
    setDescription("");
    setAmount("");
    setRecipient("");
    setImage(null);
  };

  // const { isMember, isStakeholder, loading } = useData();
  // if (loading) return <div>Loading...</div>;
  return (
    <div className={styles.container}>
      <Head>
        <title>DAOmocles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* {isMember && ( */}
      {true && (
        <main className="w-full flex flex-col py-4 flex-grow max-w-8xl items-center">
          <div className="w-3/4 border-2 border-blue-600 rounded-xl p-3 mt-10">
            <div className="flex flex-col justify-center">
              {/* <span className="text-xl text-center">Create a new Proposal</span> */}
              <p className="mt-4 w-full flex flex-wrap items-center justify-between">
                
                <div>
                  Month &nbsp;

                  <select className="px-3 py-1 border border-black rounded-xl text-black" name="Months" id="months">
                    <option value="Jan">Jan</option>
                    <option value="Feb">Feb</option>
                    <option value="Mar">Mar</option>
                    <option value="Apr">Apr</option>
                    <option value="May">May</option>
                    <option value="Jun">Jun</option>
                    <option value="Jul">Jul</option>
                    <option value="Aug">Aug</option>
                    <option value="Sep">Sep</option>
                    <option value="Oct">Oct</option>
                    <option value="Nov">Nov</option>
                    <option value="Dec">Dec</option>
                  </select>

                  &emsp; Tags &nbsp;
                  <select className="px-3 py-1 border border-black rounded-xl text-black" name="Labels" id="labels">
                    <option value="Marketing">Marketing</option>
                    <option value="Contribution">Contribution</option>
                    <option value="Grant">Grant</option>
                  </select>
                  &emsp;

                  <button
                    className="px-3 py-1 rounded-xl bg-blue-600 text-white"
                    type="submit"
                    name="search-button"
                    id="search-button"
                  >
                    Search
                  </button>
                </div>
                
                <div>
                  <button
                    className="px-3 py-1 rounded-xl bg-black text-white"
                    type="submit"
                    name="search-button"
                    id="search-button"
                  >
                    Edit
                  </button>
                </div>

              </p>
              
              <p className="mt-4 flex flex-col justify-center" id="table">
                <table className="table-fixed border-black border">
                  <thead className="border-black border max-w-xs">
                    <tr>
                      <th>Item Name</th>
                      <th>Descriptions</th>
                      <th>Label</th>
                      <th>Network</th>
                      <th>Asset</th>
                      <th>Value</th>
                      <th>Time</th>
                    </tr>
                  </thead>
                  <tbody className="mt-4 max-w-xs">
                    <div>
                      <tr>
                        <td>name 1</td>
                        <td>here is the description</td>
                        <td>Marketing</td>
                        <td>Eth</td>
                        <td>eth</td>
                        <td>13</td>
                        <td>2023-03-02</td>
                      </tr>
                    </div>
                    <tr>
                      <td>name 1</td>
                      <td>here is the description</td>
                      <td>Marketing</td>
                      <td>Eth</td>
                      <td>eth</td>
                      <td>13</td>
                      <td>2023-03-02</td>
                    </tr>
                    <tr>
                      <td>name 1</td>
                      <td>here is the description</td>
                      <td>Marketing</td>
                      <td>Eth</td>
                      <td>eth</td>
                      <td>13</td>
                      <td>2023-03-02</td>
                    </tr>
                  </tbody>
                </table>

              </p>

            </div>
          </div>
        </main>
      )}
    </div>
  );
}
